import Header from '@/components/header/main'
import './globals.css'
import Footer from '@/components/footer/main'



export const metadata = {
  title: 'fiifi-Estore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer /> 
      </body>
    </html>
  )
}
